version: "2.0"

services:
  db_master:
    image: mysql/mysql-server:8.0
    container_name: 'db_master'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: master
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 33061:3306
  db_slave:
    image: mysql/mysql-server:8.0
    container_name: 'db_slave'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slave
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 33062:3306
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.2'
    container_name: 'elasticsearch'
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.6.2'
    container_name: 'kibana'
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.my-organization.com
      ELASTICSEARCH_URL: http://elasticsearch:9200
